activation_fn: silu
atomic_type_shifts: null
avg_num_neighbors: 13.168995780096482
cutoff_fn: phys
degrees:
- 1
- 2
- 3
- 4
device: cpu
dispersion_energy_bool: true
dispersion_energy_cutoff_lr_damping: null
dispersion_energy_scale: 1.2
dtype: torch.float64
electrostatic_energy_bool: true
electrostatic_energy_scale: 4.0
energy_activation_fn: silu
energy_regression_dim: 128
features_dim: 128
input_convention: positions
layer_normalization_1: true
layer_normalization_2: true
layers_behave_like_identity_fn_at_init: false
learn_atomic_type_scales: false
learn_atomic_type_shifts: false
message_normalization: avg_num_neighbors
num_att_heads: 4
num_elements: 118
num_features_head: 32
num_interactions: 3
num_radial_basis: 32
output_is_zero_at_init: false
qk_non_linearity: identity
r_max: 4.5
r_max_lr: null
radial_basis_fn: bernstein
residual_mlp_1: true
residual_mlp_2: false
trainable_rbf: false
use_charge_embed: true
use_spin_embed: true
zbl_repulsion_bool: true
